version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5433:5432' # Only expose this if you need access from outside Docker\

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-app
    environment:
      NODE_ENV: ${NODE_ENV}
      DB_HOST: db # Use the Docker service name 'db' to connect internally
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
      MONGODB_URL: ${MONGODB_URL}
      MONGODB_NAME: ${MONGODB_NAME}
      UPLOAD_DIR: ${UPLOAD_DIR}
      API_PORT: ${API_PORT}
      API_HOST: ${API_HOST}
      API_PROTOCOL: ${API_PROTOCOL}
      IP_ADDRESS: ${IP_ADDRESS}
    ports:
      - '3000:3000'
    depends_on:
      - db

volumes:
  postgres_data:
